
services:
  happyr.translation.auto_fallback_translator:
    class: Happyr\AutoFallbackTranslationBundle\Translator\FallbackTranslator
    arguments: [~, "@happyr.translation.auto_fallback_translator.inner", ~]

