parameters:

services:
  happyr.translation.auto_fallback_translator:
    class: Happyr\AutoFallbackTranslationBundle\Service\FallbackTranslator
    arguments: [~, @happyr.translation.auto_fallback_translator.inner, ~]

